### ISSUE TITLE
estrutura_dados

### ISSUE THREAD

**Issue by vctrgalhardo** [Tecnologia-em-Banco-de-Dados-PUC-Minas/eixo5_grupo1_20241#4]
![Captura de tela 2024-03-17 182833](https://github.com/Tecnologia-em-Banco-de-Dados-PUC-Minas/eixo5_grupo1_20241/assets/138826075/6745bdbc-46cc-4e00-b656-31a393885efa)

**Comment by CarolPusceddu** [comment]
ok
